### ISSUE TITLE
Introduce a dependency autoupdate tool

### ISSUE THREAD

**Issue by omissis** [mecha-ci/hyperbuild#3]

**Comment by dirk39** [comment]
Do you want to use renovate or we can use dependabot of GitHub?

**Comment by omissis** [comment]
I guess both are fine, perhaps we could do a quick feature comparison before deciding? I'm no expert in neither, the last time I looked into them was years ago, and Renovate seemed to be a bit more flexible, but perhaps things have changed :)

**Comment by dirk39** [comment]
Ok 👍 let me prepare a comparison between those two and we decide which one to use.
