### ISSUE TITLE
Introduce github actions

### ISSUE THREAD

**Issue by omissis** [mecha-ci/hyperbuild#5]
We'll need to run a bunch of linters, as well as tests and release steps.

Depends on #6

**Comment by ludusrusso** [comment]
Do you like `golangci-lint` to manage linters?

**Comment by omissis** [comment]
Yeah, I also want to add cytopia's ones. I will push a makefile with all the things soon :)

**Comment by omissis** [comment]
here's the PR introducing the makefile: #11
